import { expect, test } from '@playwright/test'

test('pages keep their URL on refresh and support browser history and direct links', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'AI 设置', exact: true }).click()
  await expect(page).toHaveURL(/\/settings$/)
  await page.reload()
  await expect(page.getByRole('heading', { name: '连接你的 AI' })).toBeVisible()
  await page.getByLabel('站点访问口令').fill('memory-only-test-token')
  await page.getByRole('button', { name: '经历素材', exact: true }).click()
  await expect(page).toHaveURL(/\/materials$/)
  await expect(page.getByRole('button', { name: '添加经历', exact: true })).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('heading', { name: '连接你的 AI' })).toBeVisible()
  await expect(page.getByLabel('站点访问口令')).toHaveValue('memory-only-test-token')
  expect(page.url()).not.toContain('memory-only-test-token')
  await page.goForward()
  await page.reload()
  await expect(page.getByRole('button', { name: '添加经历', exact: true })).toBeVisible()
  await page.goto('/settings')
  await expect(page.getByRole('heading', { name: '连接你的 AI' })).toBeVisible()
  await page.goto('/materials')
  await expect(page.getByRole('button', { name: '添加经历', exact: true })).toBeVisible()
})

test('list filtering survives refresh and deleted document links do not render stale editors', async ({
  page,
  context,
}) => {
  await page.goto('/')
  await page.getByRole('button', { name: '空白创建', exact: true }).click()
  await expect(page).toHaveURL(/\/resumes\/[^/?]+/)
  const resumeUrl = page.url()
  await page.getByRole('button', { name: '返回简历列表', exact: true }).click()
  await page.getByRole('textbox', { name: '搜索简历', exact: true }).fill('未命名')
  await expect(page).toHaveURL(/q=/)
  await page.reload()
  await expect(page.getByRole('textbox', { name: '搜索简历', exact: true })).toHaveValue('未命名')
  const editor = await context.newPage()
  await editor.goto(resumeUrl)
  await expect(editor.getByLabel('姓名', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '删除 未命名简历', exact: true }).click()
  await page.getByRole('button', { name: '确认删除', exact: true }).click()
  await expect(editor.getByRole('heading', { name: '找不到这份简历' })).toBeVisible()
  await editor.reload()
  await expect(editor.getByRole('heading', { name: '找不到这份简历' })).toBeVisible()
})

test('resume ID, editor tab and mobile preview survive refresh and direct navigation', async ({
  page,
  context,
}) => {
  await page.goto('/')
  await page.getByRole('button', { name: '空白创建', exact: true }).click()
  await expect(page).toHaveURL(/\/resumes\/[^/?]+/)
  const resumeUrl = new URL(page.url())
  await page.getByLabel('姓名', { exact: true }).fill('路由测试用户')
  await page.getByLabel('姓名', { exact: true }).blur()
  await page.getByRole('button', { name: /^AI 建议/ }).click()
  await expect(page).toHaveURL(/tab=ai/)
  const aiUrl = page.url()
  await page.reload()
  await expect(page.getByLabel('目标岗位', { exact: true })).toBeVisible()
  await expect(page.getByTestId('resume-paper')).toContainText('路由测试用户')
  const other = await context.newPage()
  await other.goto(aiUrl)
  await expect(other.getByLabel('目标岗位', { exact: true })).toBeVisible()
  await other.close()
  await page.getByRole('button', { name: '修改记录', exact: true }).click()
  await expect(page).toHaveURL(/tab=history/)
  await page.goBack()
  await expect(page.getByLabel('目标岗位', { exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '查看预览', exact: true }).click()
  await expect(page).toHaveURL(/preview=true/)
  await page.reload()
  await expect(page.getByRole('button', { name: '返回编辑', exact: true })).toBeVisible()
  await expect(page.getByTestId('preview-page').first()).toBeVisible()
  await page.goto(`${resumeUrl.pathname}?tab=invalid&preview=invalid`)
  await expect(page.getByLabel('姓名', { exact: true })).toHaveValue('路由测试用户')
  await expect(page.getByRole('button', { name: '查看预览', exact: true })).toBeVisible()
})

test('unknown routes and missing resumes show a useful recovery page', async ({ page }) => {
  await page.goto('/does-not-exist')
  await expect(page.getByRole('heading', { name: '页面不存在' })).toBeVisible()
  await page.getByRole('button', { name: '返回简历列表', exact: true }).click()
  await expect(page).toHaveURL(/\/$/)
  await page.goto('/resumes/missing-document')
  await expect(page.getByRole('heading', { name: '找不到这份简历' })).toBeVisible()
  await expect(page).toHaveURL(/\/resumes\/missing-document$/)
  await page.getByRole('button', { name: '返回简历列表', exact: true }).click()
  await expect(page.getByRole('button', { name: '空白创建', exact: true })).toBeVisible()
})
